react:
  build: .
  ports:
    - '3000:3000'
  volumes:
    - .:/home/appuser/workdir
    - /home/appuser/workdir/node_modules
python:
  build: ./server
  ports:
    - '8765:8765'
  volumes:
    - .:/home/appuser/workdir